service: first-deploy

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: whenu-serverless-poc
      localDir: dummy

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: whenu-serverless-poc
